researchpaper/urls.py
from django.contrib import admin
from django.urls import path
from research import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home),
    path('login/',views.login),
    path('teacherview/',views.teachview),
    path('edit/<int:id>',views.edit,name='edit'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('add/',views.add,name='add'),
    path('addnew/<int:id>',views.addnew,name='addnew'),
    path('viewers/',views.viewers_page,name='viewers_page'),
    path('view2/<str:name>',views.viewers_info,name='view2'),
]

research/models.py
from django.db import models

# Create your models here.
class teacher(models.Model) :
    email=models.EmailField()
    password=models.CharField(max_length=20)
class researchpapers(models.Model) :
    tname=models.CharField(max_length=30)
    tdept=models.CharField(max_length=20)
    tid=models.CharField(max_length=10)
    temail=models.CharField(max_length=30)
    ptitle=models.CharField(max_length=100)
    pdate=models.CharField(max_length=30)
    pdesc=models.CharField(max_length=100)
    pnat=models.CharField(max_length=20)
    ptype=models.CharField(max_length=20)
    pssn=models.CharField(max_length=20)
    pfield=models.CharField(max_length=30)
    plink=models.CharField(max_length=400)

research/forms.py
from django import forms
from research.models import researchpapers

class paperform(forms.ModelForm):
    class Meta :
            model=researchpapers
            fields="__all__"

research/views.py
from django.shortcuts import render,redirect

# Create your views here.
from research.models import teacher,researchpapers
from django.contrib import messages
from django.http import HttpResponse
from .forms import paperform

# Create your views here.
def home(request):
    return render(request,"homepage.html")

def login(request) :
    if request.method=='POST' :
        global username
        username=request.POST['username']
        password=request.POST['password']
        teach_list=teacher.objects.all()
        for i in teach_list :
            if i.email==username and i.password==password:
                return redirect("/teacherview")
        else :
            messages.info(request,'Invalid username or password')
            return redirect('/login')
    else  :
        return render(request,'login.html')

def teachview(request) :
    research=researchpapers.objects.all()
    return render(request,'teachview.html',{'research':research,'username':username})

def delete(request, id):
        record_to_delete =researchpapers.objects.get(id=id)
        record_to_delete.delete()
        return redirect('/teacherview/')

def edit(request, id):
    research=researchpapers.objects.get(id=id)
    return render(request, 'edit.html', {'research':research})

def update(request,id) :
    research=researchpapers.objects.get(id=id)
    form=paperform(request.POST,instance=research)
    if (form.is_valid()):
        form.save()
        return redirect('/teacherview/')
    return render(request,'edit.html',{'research':research,'username':username})

def add(request):
    research=researchpapers.objects.all()
    for i in research:
        if i.temail==username:
            res=i
            break
    res.pk=None
    res.save()
    return render(request, 'add.html', {'res':res})

def addnew(request,id):
    research=researchpapers.objects.get(id=id)
    form=paperform(request.POST,instance=research)
    if (form.is_valid()):
        form.save()
        return redirect('/teacherview/')
    return render(request,'add.html',{'research':research})


def viewers_page(request):
    research = researchpapers.objects.all()
    research_math = set()
    research_cse = set()
    research_eee = set()
    research_it = set()

    for i in research:
        if i.tdept == 'Mathematics':
            research_math.add(i.tname)
        elif i.tdept == 'CSE':
            research_cse.add(i.tname)
        elif i.tdept == 'IT':
            research_it.add(i.tname)
        elif i.tdept == 'EEE':
            research_eee.add(i.tname)

    return render(request, 'viewers.html', {'research_math': research_math,'research_cse': research_cse,'research_it': research_it,'research_eee': research_eee})

def viewers_info(request,name) :
    research=researchpapers.objects.filter(tname=name)
    return render(request, 'view2.html', {'research':research})

templates/add.html
<html>
    <head>
        <title>123</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <style>
        .navbar-brand{
    color: #FFF9C9;
    font-weight: bold;
    font-family:Georgia, 'Times New Roman', Times, serif;
}
body {
  background-image: url('https://images.squarespace-cdn.com/content/v1/5e077e3c19536970a2d5defa/3c2069e9-780a-4c59-ba86-c3b3c4e169e9/beauty_background_3.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
.selectWrapper{
  outline: none;
  border-radius:36px;
  display:inline-block;
  overflow:hidden;
  background:#cccccc;
}
.custom-select.d-block.w-800 {
    width: 800px;
    border: 1px solid #862B0D;
    -webkit-border-top-right-radius: 15px;
    -webkit-border-bottom-right-radius: 15px;
    -moz-border-radius-topright: 15px;
    -moz-border-radius-bottomright: 15px;
    border-top-right-radius: 15px;
    border-bottom-right-radius: 15px;
    padding: 2px;
  }
#nat{
  border-radius: 15px;
width:150px;
}
#state{
  border-radius: 15px;
width:150px;
}
</style>
    <body>
        <nav class="navbar" style="background-color: #862B0D;">
            <div class="container-fluid">
              <a class="navbar-brand" href="https://www.cbit.ac.in/" target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/en/6/68/Chaitanya_Bharathi_Institute_of_Technology_logo.png" alt="Logo" width="30" height="34" class="d-inline-block align-text-top">
                <span style="vertical-align: middle">&nbsp;Chaitanya Bharathi Institute of Technology</span>
              </a>

              <form class="d-flex" role="search">
                <a href="/home/"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16" style="color: #FFF9C9;">
                  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
                </svg></a>
              </form>
            </div>
        </nav>

        <div class="container">
            <div class="py-5 text-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-box-arrow-in-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                  </svg>
                  <br>
              <h2><b>Add</b></h2>
            </div>
            <div class="row">
              <div class="col-2">

              </div>
              <div class="col-8">
                <h4 class="mb-3">Add your work: </h4>
                
                <form method="POST" action="/addnew/{{res.id}}" class="needs-validation" novalidate="">
                      {% csrf_token%}
                  <input type="hidden" class="form-control" name="tname" id="id_tname"  value="{{res.tname}}" >
                <input type="hidden" class="form-control" name="tdept" id="id_tdept" value="{{res.tdept}}" >
                <input type="hidden" class="form-control" name="tid" id="id_tid"  value="{{res.tid}}" >
                <input type="hidden" class="form-control" name="temail" id="id_temail"  value="{{res.temail}}" >
                      <label for="firstName">Name of Paper<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label>
                      <input type="text" class="form-control" name="ptitle" id="id_ptitle" placeholder=""  required="">
                      <div class="invalid-feedback">
                        Please enter a valid research paper name.
                  </div><br>
                  <label for="date">Date of Publishing<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
    <div class="row justify-content">
        <div class="col-5">
            <input type="text" id="id_pdate" name="pdate" class="form-control"   />
            
        </div>
    </div><br>
                  <div class="mb-3">
                    <label for="desc">Description <span class="text-muted">(Optional)</span></label>
                    <input type="text" class="form-control" id="id_pdesc" placeholder="A few lines about your work"  name="pdesc" >
                  </div><br>


                  <div class="row">
                    <div class="col-md-5 mb-3">
                      <label for="nat">National/International<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <br>

                      <input type="text" class="form-control"  id="id_pnat" name="pnat"  required="">

                      <div class="invalid-feedback">
                        Please select a valid option.
                      </div>
                    </div>
                    <div class="col-md-4 mb-3">
                      <label for="state">Journal/Conference<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <br>
                      <input type="text" class="form-control" id="id_ptype" name="ptype" required="" >
                        
                      <div class="invalid-feedback">
                        Please select a valid option.
                      </div>
                    </div>
                    <div class="col-md-3 mb-3">
                      <label for="zip">ISSN Code: <span class="text-muted">(Optional)</span></label>
                      <input type="text" class="form-control" id="id_pssn" name="pssn" placeholder="" required="" default="-" >
                      <div class="invalid-feedback">
                        Zip code required.
                      </div>
                    </div>
                    <div class="mb-3">
                      <label for="field">Field of Research<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <input type="text" class="form-control" id="id_pfield" name="pfield" placeholder="Mathematics, Chemistry..." required="" >
                      <div class="invalid-feedback">
                        Please enter a correct field.
                      </div>
                    </div>
        
                    <div class="mb-3">
                      <label for="link">Link<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <input type="text" class="form-control" id="id_plink" name="plink" required=" " placeholder="Provide a link to view your work" >
                    </div>

                  <div class="col-3">
                  <button class="btn btn-primary btn-lg btn-block" type="submit" style="background-color: #9f330f;">Add</button>
                </form>
          </div>

          

    </body>
</html>

templates/edit.html
<html>
    <head>
        <title>update research paper</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <style>
        .navbar-brand{
    color: #FFF9C9;
    font-weight: bold;
    font-family:Georgia, 'Times New Roman', Times, serif;
}
body {
  background-image: url('https://images.squarespace-cdn.com/content/v1/5e077e3c19536970a2d5defa/3c2069e9-780a-4c59-ba86-c3b3c4e169e9/beauty_background_3.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
.selectWrapper{
  outline: none;
  border-radius:36px;
  display:inline-block;
  overflow:hidden;
  background:#cccccc;
}
.custom-select.d-block.w-800 {
    width: 800px;
    border: 1px solid #862B0D;
    -webkit-border-top-right-radius: 15px;
    -webkit-border-bottom-right-radius: 15px;
    -moz-border-radius-topright: 15px;
    -moz-border-radius-bottomright: 15px;
    border-top-right-radius: 15px;
    border-bottom-right-radius: 15px;
    padding: 2px;
  }
#nat{
  border-radius: 15px;
width:150px;
}
#state{
  border-radius: 15px;
width:150px;
}
</style>
    <body>
        <nav class="navbar" style="background-color: #862B0D;">
            <div class="container-fluid">
              <a class="navbar-brand" href="https://www.cbit.ac.in/" target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/en/6/68/Chaitanya_Bharathi_Institute_of_Technology_logo.png" alt="Logo" width="30" height="34" class="d-inline-block align-text-top">
                <span style="vertical-align: middle">&nbsp;Chaitanya Bharathi Institute of Technology</span>
              </a>

              <form class="d-flex" role="search">
                
                <a href="/home/"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16" style="color: #FFF9C9;">
                  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
                </svg></a>
              </form>
            </div>
        </nav>

        <div class="container">
            <div class="py-5 text-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor" class="bi bi-box-arrow-in-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                  </svg>
                  <br>
              <h2><b>Update</b></h2>
            </div>
            <div class="row">
              <div class="col-2">

              </div>
              
              <div class="col-8">
                <h4 class="mb-3">Update your work: </h4>
                <form method="POST" action="/update/{{research.id}}" class="needs-validation" novalidate="">
                  {% csrf_token%}
                  <input type="hidden" class="form-control" name="tname" id="id_tname"  value="{{research.tname}}" >
                <input type="hidden" class="form-control" name="tdept" id="id_tdept" value="{{research.tdept}}" >
                <input type="hidden" class="form-control" name="tid" id="id_tid"  value="{{research.tid}}" >
                <input type="hidden" class="form-control" name="temail" id="id_temail"  value="{{research.temail}}" >
                      <label for="firstName">Name of Paper<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label>
                      <input type="text" class="form-control" name="ptitle" id="id_ptitle" placeholder="" value="{{research.ptitle}}" required="">
                      <div class="invalid-feedback">
                        Please enter a valid research paper name.
                  </div><br>
                  <label for="date">Date of Publishing<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
    <div class="row justify-content">
        <div class="col-5">
            <input type="text" id="id_pdate" name="pdate" class="form-control" value="{{research.pdate}}"  />
            
        </div>
    </div><br>
                  <div class="mb-3">
                    <label for="desc">Description <span class="text-muted">(Optional)</span></label>
                    <input type="text" class="form-control" id="id_pdesc" placeholder="A few lines about your work"  name="pdesc" value="{{research.pdesc}}">
                  </div><br>


                  <div class="row">
                    <div class="col-md-5 mb-3">
                      <label for="nat">National/International<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <br>

                      <input type="text" class="form-control"  id="id_pnat" name="pnat" value="{{research.pnat}}" required="">

                      <div class="invalid-feedback">
                        Please select a valid option.
                      </div>
                    </div>
                    <div class="col-md-4 mb-3">
                      <label for="state">Journal/Conference<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <br>
                      <input type="text" class="form-control" id="id_ptype" name="ptype" required="" value="{{research.ptype}}">
                        
                      <div class="invalid-feedback">
                        Please select a valid option.
                      </div>
                    </div>
                    <div class="col-md-3 mb-3">
                      <label for="zip">ISSN Code: <span class="text-muted">(Optional)</span></label>
                      <input type="text" class="form-control" id="id_pssn" name="pssn" placeholder="" required="" value="{{research.pssn}}">
                      <div class="invalid-feedback">
                        Zip code required.
                      </div>
                    </div>
                    <div class="mb-3">
                      <label for="field">Field of Research<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <input type="text" class="form-control" id="id_pfield" name="pfield" placeholder="Mathematics, Chemistry..." required="" value="{{research.pfield}}">
                      <div class="invalid-feedback">
                        Please enter a correct field.
                      </div>
                    </div>
        
                    <div class="mb-3">
                      <label for="link">Link<span class="mand" style="color: #9f330f;">&nbsp;*</span></label></label></label>
                      <input type="text" class="form-control" id="id_plink" name="plink" required=" " placeholder="Provide a link to view your work" value="{{research.plink}}">
                    </div>

                  <div class="col-3">
                  <button class="btn btn-primary btn-lg btn-block" type="submit" style="background-color: #9f330f;">Update</button>
                </form>
          </div>

          

    </body>
</html>

templates/homepage.html
<html>
<head>
    <title>Homepage</title>
    <link rel="icon" type="image/x-icon" href="/fav/favicon.ico">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
<style>
  body {
  background-image:url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfglaoaB-qMdiWpZVIF6ttdRxSjmZ5Csv5sg&usqp=CAU');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
    /* Float four columns side by side */
.column {
  float: left;
  width: 25%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding in columns */
.row {margin: 0 -5px;}

.navbar-brand{
    color: FFF9C9;
    font-weight: bold;
    font-family:Georgia, 'Times New Roman', Times, serif;
}

h1{
    font-weight: bold;
    font-family:Georgia, 'Times New Roman', Times, serif;
}

.card{
    color: whitesmoke;
    margin-right:54px;
}

</style>
</head>
<body onload=typeWriter()>

    <nav class="navbar" style="background-color: #862B0D;">
        <div class="container-fluid">
          <a class="navbar-brand" href="https://www.cbit.ac.in/" target="_blank">
            <img src="https://upload.wikimedia.org/wikipedia/en/6/68/Chaitanya_Bharathi_Institute_of_Technology_logo.png" alt="Logo" width="30" height="34" class="d-inline-block align-text-top">
            <span>&nbsp;Chaitanya Bharathi Institute of Technology</span>
          </a>
        </div>
      </nav>
<br>
    <center><h1>Research Paper Management System</h1>
    
    <br>
    <br>
    <br>
    <br>


        <section class="features3 cid-rym4BqMZP3" id="features05-3t">

    

    
          <div class="container">
              <div class="row">
                  <div class="card p-3 col-md-8 col-lg-4"  style="background-color: #862B0D;">
                      <div class="card-wrapper card1">
                          <div class="card-box">
                              <div class="card-img">
                                  <span class="mbr-iconfont mobi-mbri-preview mobi-mbri"></span>
                              </div>
                              
                              <img src="https://images.template.net/wp-content/uploads/2017/06/Research-Papers.jpg" class="card-img-top" alt="...">
                              <h4 class="card-title align-center mbr-bold mbr-white mbr-fonts-style display-5">Research Papers</h4>
                              <p class="mbr-text align-center mbr-white mbr-fonts-style display-7">This page is to view professor's research papers.</p>
                              <div class="mbr-section-btn align-center"><a href="/viewers" class="btn btn-md btn-white-outline display-4"  style="color: #FFC95F;">Click Here</a>
                              </div>
                          </div>
      
                      </div>
                  </div>
                  <div class="col-3">

                  </div>
                  <div class="card p-3 col-md-8 col-lg-4"   style="background-color: #862B0D;">
                      <div class="card-wrapper card2">
                          <div class="card-box">
                              <div class="card-img">
                                  <span class="mbr-iconfont mobi-mbri-globe mobi-mbri"></span>
                              </div>
                              
                              <img src="https://www.mapua.edu.ph/blog/wp-content/uploads/2016/07/Prof_blog20FA-1024x576.jpg" class="card-img-top" alt="...">
                              <h4 class="card-title align-center mbr-bold mbr-white mbr-fonts-style display-5">Professor's Page
                              </h4>
                              <p class="mbr-text align-center mbr-white mbr-fonts-style display-7">This professor's homepage to post and update their work.</p>
                              <div class="mbr-section-btn align-center"><a href="/login" class="btn btn-md btn-white-outline display-4" style="color: #FFC95F;">Click Here</a>
                              </div>
                          </div>
      
                      </div>
                  </div>    
                  
              </div>
          </div>
      </section>
    </div>
</center>
</body>
</html>

templates/view2.html
<html>
    <head>
        <title>Teacher View</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
       .navbar-brand{
    color: #FFF9C9;
    font-weight: bold;
    font-family:Georgia, 'Times New Roman', Times, serif;
}
body {
  background-image: url('https://images.template.net/97252/sage-green-background-0un6c.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

table {
      width: 100%;
      border-collapse: collapse;
    }
    
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
    
    tr:hover {
      background-color: #f5f5f5;
    }

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
        </style>
        </head>
        <body>
          <nav class="navbar" style="background-color: #862B0D;">
            <div class="container-fluid">
              <a class="navbar-brand" href="https://www.cbit.ac.in/" target="_blank">
                <img src="https://upload.wikimedia.org/wikipedia/en/6/68/Chaitanya_Bharathi_Institute_of_Technology_logo.png" alt="Logo" width="30" height="34" class="d-inline-block align-text-top">
                <span style="vertical-align: middle">&nbsp;Chaitanya Bharathi Institute of Technology</span>
              </a>

              <form class="d-flex" role="search">
                <a href="/home/"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16" style="color: #FFF9C9;">
                  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
                </svg></a>
              </form>
            </div>
        </nav>
        <br>
        
        <div id="main">
          <center>
          <h1>Research Papers</h1>
          <p>CBIT Research</p>
          </center>
  <table>
    <tr style="background-color: #f5f5f5;">
      <th>Title</th>
      <th>Date</th>
      <th>Description</th>
      <th>National/International</th>
      <th>Journal/Conference</th>
      <th>ISSN Code</th>
      <th>Field</th>
      <th>Link</th>
    </tr>
    {% for res in research %}
    <tr>
      <td>{{res.ptitle}}</td>
      <td>{{res.pdate}}</td>
      <td>{{res.pdesc}}</td>
      <td>{{res.pnat}}</td>
      <td>{{res.ptype}}</td>
      <td>{{res.pssn}}</td>
      <td>{{res.pfield}}</td>
      <td><a href="{{res.plink}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16" style="color:#862B0D">
        <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.002 1.002 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"/>
        <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243L6.586 4.672z"/>
      </svg></a></td>
    </tr>
    {% endfor %}
    <!-- Add more rows for additional research papers -->
  </table>
        </div>
        </body>
</html>